[package]
name = "itch_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
flate2 = "1.0.34"
byteorder = "1.5.0"
csv = "1.3.0"
serde = { version = "1.0.214", features = ["derive"] }
